export const ITINERARY_CONSTANTS = {
  DAYS_PER_ITINERARY: 2,
  MINUTES_PER_HOUR: 60,
  HOURS_PER_DAY: 24,
  RELATED_ITINERARIES_LIMIT: 3,
  METADATA_PILL_BORDER_RADIUS: 20,
  DAY_TAB_BORDER_RADIUS: 20,
  ITINERARY_CARD_WIDTH: 280,
  ITINERARY_CARD_BORDER_RADIUS: 16,
  ITINERARY_IMAGE_HEIGHT: 180,
  IMAGE_OVERLAY_SIZE: 36,
  IMAGE_OVERLAY_BORDER_RADIUS: 20,
  IMAGE_OVERLAY_OPACITY: 0.3,
} as const;

export const ACTIVITY_LEVELS = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
} as const;

export type ActivityLevel = typeof ACTIVITY_LEVELS[keyof typeof ACTIVITY_LEVELS];
