import type {
  EventReward,
  LinkedCard,
  MerchantOffer,
  RewardActivity,
  WalletBalance,
} from '@/types/wallet.types';

export const MOCK_BALANCE: WalletBalance = {
  available: 28.5,
  pending: 12.0,
  lifetime: 144.0,
  currency: 'GBP',
};

export const MOCK_LINKED_CARD: LinkedCard = {
  id: 'card-1',
  lastFour: '4242',
  brand: 'visa',
  isActive: true,
};

export const MOCK_EVENT_REWARDS: EventReward[] = [
  {
    id: 'er-1',
    eventId: 'evt-afronation',
    eventName: 'AfroNation Weekend',
    eventEmoji: '🎉',
    expiresAt: Date.now() + 1000 * 60 * 60 * 24 * 5,
    rewards: [
      {
        id: 'r-1',
        description: 'Partner restaurants',
        type: 'cashback',
        value: '10% cashback',
        emoji: '🍽️',
      },
      {
        id: 'r-2',
        description: 'Grooming partners',
        type: 'discount',
        value: '15% off',
        emoji: '💈',
      },
      {
        id: 'r-3',
        description: 'Exclusive lounge access',
        type: 'perk',
        value: 'Lounge perks',
        emoji: '🛋️',
      },
      {
        id: 'r-4',
        description: 'Nail & beauty',
        type: 'cashback',
        value: '12% cashback',
        emoji: '💅',
      },
    ],
  },
];

export const MOCK_MERCHANTS: MerchantOffer[] = [
  {
    id: 'm-1',
    name: 'Kiza Lounge',
    category: 'Nightlife',
    rewardValue: '10% cashback',
    rewardType: 'cashback',
    imageUrl: 'https://picsum.photos/seed/kiza/400/300',
    eventId: 'evt-afronation',
    eventName: 'AfroNation Weekend',
    description: 'Upscale African lounge and restaurant. Earn 10% cashback on every visit during AfroNation Weekend.',
    terms: 'Valid on food and drinks. Cashback applied automatically via linked card.',
    address: '4 Kensington High St, London',
    isNearby: true,
  },
  {
    id: 'm-2',
    name: 'Fresh Cut Barbers',
    category: 'Grooming',
    rewardValue: '15% off',
    rewardType: 'discount',
    imageUrl: 'https://picsum.photos/seed/freshcut/400/300',
    eventId: 'evt-afronation',
    eventName: 'AfroNation Weekend',
    description: 'Premium barbershop with AfroNation Weekend exclusive 15% off all services.',
    terms: 'Discount applied at point of sale. Show your Runwae pass.',
    address: '12 Brixton Market Row, London',
    isNearby: true,
  },
  {
    id: 'm-3',
    name: 'Nail Bar Lagos',
    category: 'Beauty',
    rewardValue: '12% cashback',
    rewardType: 'cashback',
    imageUrl: 'https://picsum.photos/seed/nailbar/400/300',
    eventId: 'evt-afronation',
    eventName: 'AfroNation Weekend',
    description: 'Lagos-inspired nail and beauty bar. Earn cashback on all treatments this weekend.',
    terms: 'Cashback credited within 48 hours.',
    address: '7 Electric Ave, London',
    isNearby: false,
  },
  {
    id: 'm-4',
    name: 'Papi Chulo',
    category: 'Restaurant',
    rewardValue: 'Free drink',
    rewardType: 'perk',
    imageUrl: 'https://picsum.photos/seed/papichulo/400/300',
    eventId: 'evt-afronation',
    eventName: 'AfroNation Weekend',
    description: 'Afrobeats-inspired cocktail bar. Free welcome drink with any food purchase.',
    terms: 'One per person, per visit. Valid Fri–Sun only.',
    address: '22 Notting Hill Gate, London',
    isNearby: false,
  },
];

export const MOCK_ACTIVITY: RewardActivity[] = [
  {
    id: 'a-1',
    merchantName: 'Kiza Lounge',
    merchantCategory: 'Nightlife',
    amount: 8.5,
    currency: 'GBP',
    status: 'confirmed',
    type: 'cashback',
    description: 'Cashback earned',
    createdAt: Date.now() - 1000 * 60 * 60 * 24,
    eventName: 'AfroNation Weekend',
  },
  {
    id: 'a-2',
    merchantName: 'Nail Bar Lagos',
    merchantCategory: 'Beauty',
    amount: 4.2,
    currency: 'GBP',
    status: 'pending',
    type: 'cashback',
    description: 'Cashback pending confirmation',
    createdAt: Date.now() - 1000 * 60 * 60 * 48,
    eventName: 'AfroNation Weekend',
  },
  {
    id: 'a-3',
    merchantName: 'Fresh Cut Barbers',
    merchantCategory: 'Grooming',
    amount: 7.8,
    currency: 'GBP',
    status: 'confirmed',
    type: 'cashback',
    description: 'Cashback earned',
    createdAt: Date.now() - 1000 * 60 * 60 * 72,
    eventName: 'AfroNation Weekend',
  },
  {
    id: 'a-4',
    merchantName: 'Papi Chulo',
    merchantCategory: 'Restaurant',
    amount: 8.0,
    currency: 'GBP',
    status: 'confirmed',
    type: 'cashback',
    description: 'Cashback earned',
    createdAt: Date.now() - 1000 * 60 * 60 * 96,
    eventName: 'AfroNation Weekend',
  },
];
