import {
  Bus,
  Wifi,
  Bell,
  Luggage,
  ConciergeBell,
  Columns2,
  Presentation,
  Coffee,
  BookOpen,
  Shield,
  Languages,
  Ban,
  Ticket,
  Sandwich,
  Monitor,
  Plane,
  ShoppingBag,
  ShoppingCart,
  Image as ArtGallery,
  Flame,
} from 'lucide-react-native';

export const facilityIconMap: Record<string, React.ComponentType<any>> = {
  'Area shuttle (surcharge)': Bus,
  'Fireplace in lobby': Flame,
  'Free WiFi': Wifi,
  '24-hour front desk': Bell,
  'Luggage storage': Luggage,
  'Concierge service': ConciergeBell,
  Elevator: Columns2,
  'Conference space': Presentation,
  'Breakfast available (surcharge)': Coffee,
  Library: BookOpen,
  'Safe-deposit box at front desk': Shield,
  'Multilingual staff': Languages,
  'Smoke-free property': Ban,
  'Tours/ticket assistance': Ticket,
  'Snack bar/deli': Sandwich,
  'Computer station': Monitor,
  'Airport transportation - pickup (surcharge)': Plane,
  'Airport transportation - drop-off (surcharge)': Plane,
  'Designer stores on site': ShoppingBag,
  'Shopping mall on site': ShoppingCart,
  'Art gallery on site': ArtGallery,
};
