/* eslint-disable no-console */
// Regenerate non-English locale message files from the canonical en-GB.json.
//
// Usage:
//   pnpm --filter @runwae/i18n i18n:generate              # all 5 target locales
//   pnpm --filter @runwae/i18n i18n:generate -- --locale=fr-FR  # one locale
//   pnpm --filter @runwae/i18n i18n:generate -- --dry-run       # don't write
//
// Requires `ANTHROPIC_API_KEY` in the env. Uses prompt caching on the
// source content so multi-locale runs only pay for the target instructions.
//
// en-US is NOT generated by this script — it's the canonical en-GB plus a
// small overrides file maintained by hand at messages/en-US.overrides.json.

import Anthropic from "@anthropic-ai/sdk";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const MESSAGES_DIR = join(__dirname, "..", "messages");
const SOURCE_PATH = join(MESSAGES_DIR, "en-GB.json");

const MODEL = "claude-haiku-4-5-20251001";

const TARGET_LOCALES = [
  { code: "fr-FR", name: "French (France)", notes: "Use formal `vous` in business surfaces (payment, errors); informal `tu` in friendly onboarding copy. Standard metropolitan French." },
  { code: "es-MX", name: "Spanish (Mexico, LATAM)", notes: "Latin American Spanish, neutral toward Mexican usage. Use `tú` informally throughout. Avoid Iberian-only vocabulary (e.g. `vosotros`, `coger`)." },
  { code: "es-ES", name: "Spanish (Spain)", notes: "Castilian Spanish. `tú` informally, `usted` only in formal payment/security surfaces. Use Iberian conventions (e.g. `móvil` for phone, `ordenador` for computer)." },
  { code: "pt-BR", name: "Portuguese (Brazil)", notes: "Brazilian Portuguese. Use `você` throughout (Brazilian default, not formal). Avoid European Portuguese conjugations and vocabulary." },
  { code: "it-IT", name: "Italian (Italy)", notes: "Standard Italian. Informal `tu` in onboarding/home; formal `Lei` in payment and security surfaces." },
] as const;

// Brand and product nouns that must NOT be translated. Add to this list
// when introducing new feature names.
const GLOSSARY_VERBATIM = [
  "Runwae",
  "Discover",
  "Stays",
  "Fly",
  "Do",
  "Eat & Drink",
  "Attend",
  "Shop",
  "Relax",
  "Adventure",
  "Explore",
  "Apple",
  "Google",
  "Stripe",
];

function buildSystemPrompt(): string {
  return `You translate UI strings for Runwae, a social trip-planning travel app, from British English to other locales.

Hard rules:
1. Preserve the exact JSON structure of the input. Same keys, same nesting, same array lengths.
2. Preserve ICU MessageFormat syntax exactly: \`{name}\`, \`{count, plural, one {...} other {...}}\`, \`{email}\`. The placeholder names stay in English.
3. Never translate these brand/product nouns; keep them verbatim: ${GLOSSARY_VERBATIM.join(", ")}.
4. Keep punctuation, capitalization, and tone appropriate to the locale (sentence case in body copy, title case in section headers — match the source).
5. Use the locale's native typography (e.g. French uses « » guillemets and non-breaking spaces before : ; ! ?; Spanish uses ¿ ? and ¡ !).
6. Keep strings concise. Mobile UI has limited horizontal space — if a translation is significantly longer than the source, prefer a shorter natural phrasing.
7. For \`common.errors\`, \`payment.errors\`, and \`auth.*.errors\`: be clear, calm, and actionable. No exclamation marks, no jargon.
8. Output a single JSON object. No prose, no Markdown fences, no commentary.

Tone: warm, energetic travel-platform voice. Confident but not pushy. The app is for adults aged 18-50 planning trips with friends.`;
}

function buildUserPrompt(
  sourceJson: string,
  target: (typeof TARGET_LOCALES)[number],
): string {
  return `Translate the following en-GB messages to ${target.name} (locale code: ${target.code}).

Locale-specific notes:
${target.notes}

Output the translated JSON object only. Same structure as the input.

Input:
${sourceJson}`;
}

interface CliArgs {
  locale?: string;
  dryRun: boolean;
}

function parseArgs(): CliArgs {
  const args: CliArgs = { dryRun: false };
  for (const raw of process.argv.slice(2)) {
    if (raw === "--dry-run") args.dryRun = true;
    else if (raw.startsWith("--locale=")) args.locale = raw.slice("--locale=".length);
  }
  return args;
}

function validateStructure(source: unknown, target: unknown, path = ""): string[] {
  const errors: string[] = [];
  if (typeof source !== typeof target) {
    errors.push(`${path || "<root>"}: expected ${typeof source}, got ${typeof target}`);
    return errors;
  }
  if (source && typeof source === "object" && !Array.isArray(source)) {
    const s = source as Record<string, unknown>;
    const t = target as Record<string, unknown>;
    for (const key of Object.keys(s)) {
      if (!(key in t)) {
        errors.push(`${path}${path ? "." : ""}${key}: missing in translation`);
        continue;
      }
      errors.push(...validateStructure(s[key], t[key], `${path}${path ? "." : ""}${key}`));
    }
  }
  return errors;
}

async function translateLocale(
  client: Anthropic,
  sourceJson: string,
  target: (typeof TARGET_LOCALES)[number],
): Promise<unknown> {
  const response = await client.messages.create({
    model: MODEL,
    max_tokens: 8192,
    system: [
      {
        type: "text",
        text: buildSystemPrompt(),
        cache_control: { type: "ephemeral" },
      },
    ],
    messages: [
      {
        role: "user",
        content: [
          {
            type: "text",
            text: buildUserPrompt(sourceJson, target),
          },
        ],
      },
    ],
  });

  const first = response.content[0];
  if (!first || first.type !== "text") {
    throw new Error(`Unexpected response shape for ${target.code}`);
  }
  const text = first.text.trim();
  // Strip code fences if the model wraps the JSON anyway.
  const cleaned = text
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/```\s*$/i, "")
    .trim();
  try {
    return JSON.parse(cleaned);
  } catch (err) {
    throw new Error(
      `Failed to parse JSON for ${target.code}: ${(err as Error).message}\n\n${cleaned.slice(0, 400)}…`,
    );
  }
}

async function main() {
  const args = parseArgs();

  if (!process.env.ANTHROPIC_API_KEY) {
    console.error("ANTHROPIC_API_KEY is required");
    process.exit(1);
  }

  const sourceJson = readFileSync(SOURCE_PATH, "utf8");
  const source = JSON.parse(sourceJson);

  const client = new Anthropic();

  const targets = args.locale
    ? TARGET_LOCALES.filter((l) => l.code === args.locale)
    : TARGET_LOCALES;

  if (targets.length === 0) {
    console.error(
      `Unknown locale "${args.locale}". Supported: ${TARGET_LOCALES.map((l) => l.code).join(", ")}`,
    );
    process.exit(1);
  }

  for (const target of targets) {
    console.log(`→ ${target.code}…`);
    const translated = await translateLocale(client, sourceJson, target);
    const errs = validateStructure(source, translated);
    if (errs.length > 0) {
      console.error(`✗ ${target.code} failed structural validation:`);
      for (const e of errs.slice(0, 10)) console.error(`   ${e}`);
      if (errs.length > 10) console.error(`   …and ${errs.length - 10} more`);
      process.exitCode = 1;
      continue;
    }
    if (args.dryRun) {
      console.log(`✓ ${target.code} (dry run — not written)`);
      continue;
    }
    const outPath = join(MESSAGES_DIR, `${target.code}.json`);
    writeFileSync(outPath, JSON.stringify(translated, null, 2) + "\n");
    console.log(`✓ ${target.code} → ${outPath}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
