export const getCurrencySymbol = (currency: string = 'USD'): string => {
  const symbols: Record<string, string> = {
    USD: '$',
    EUR: '€',
    GBP: '£',
    JPY: '¥',
    CNY: '¥',
    KRW: '₩',
    INR: '₹',
    BRL: 'R$',
    MXN: '$',
    CAD: 'CA$',
    AUD: 'A$',
    NZD: 'NZ$',
    CHF: 'CHF',
    SEK: 'kr',
    NOK: 'kr',
    DKK: 'kr',
    SGD: 'S$',
    HKD: 'HK$',
    AED: 'د.إ',
    SAR: '﷼',
    ZAR: 'R',
    TRY: '₺',
    RUB: '₽',
    THB: '฿',
    MYR: 'RM',
    IDR: 'Rp',
    PHP: '₱',
    VND: '₫',
    EGP: 'E£',
    NGN: '₦',
    GHS: 'GH₵',
    KES: 'KSh',
    PKR: '₨',
    BDT: '৳',
    QAR: 'QR',
    KWD: 'KD',
    BHD: 'BD',
    OMR: 'OMR',
    JOD: 'JD',
    ILS: '₪',
    CZK: 'Kč',
    HUF: 'Ft',
    PLN: 'zł',
    RON: 'lei',
    HRK: 'kn',
    BGN: 'лв',
    ISK: 'kr',
    MAD: 'MAD',
    TWD: 'NT$',
  };

  return symbols[currency.toUpperCase()] ?? currency;
};
